// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-patients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) throw new Error("N\xE3o autenticado.");
  return supabaseForUser(ctx);
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-patients.ts
var list_patients_default = defineTool({
  name: "list_patients",
  title: "Listar pacientes",
  description: "Lista pacientes da cl\xEDnica com filtros opcionais por nome/CPF/telefone, status de CRM e situa\xE7\xE3o ativa.",
  inputSchema: {
    search: z.string().trim().optional().describe("Busca por nome, CPF ou telefone."),
    crm_status: z.string().trim().optional().describe("Filtra pelo status de CRM (ex.: em_acompanhamento, perdido)."),
    is_active: z.boolean().optional().describe("Filtra pacientes ativos ou inativos."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, crm_status, is_active, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      let query = supabase.from("patients").select(
        "id,name,cpf,phone,email,birth_date,is_active,crm_status,crm_tags,registration_date,referral_source"
      ).order("name").limit(limit ?? 50);
      if (search) query = query.or(`name.ilike.%${search}%,cpf.ilike.%${search}%,phone.ilike.%${search}%`);
      if (crm_status) query = query.eq("crm_status", crm_status);
      if (typeof is_active === "boolean") query = query.eq("is_active", is_active);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return ok({ count: data?.length ?? 0, patients: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/get-patient.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_patient_default = defineTool2({
  name: "get_patient",
  title: "Detalhes do paciente",
  description: "Retorna o cadastro completo de um paciente e suas consultas mais recentes.",
  inputSchema: {
    patient_id: z2.string().uuid().describe("ID do paciente."),
    appointments_limit: z2.number().int().min(0).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, appointments_limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data: patient, error } = await supabase.from("patients").select("*").eq("id", patient_id).maybeSingle();
      if (error) return fail(error.message);
      if (!patient) return fail("Paciente n\xE3o encontrado.");
      const { data: appointments } = await supabase.from("appointments").select(
        "id,appointment_date,appointment_time,status,type,modality,consultation_value,payment_status,is_package,package_session_number,package_total_sessions,professionals(name)"
      ).eq("patient_id", patient_id).order("appointment_date", { ascending: false }).limit(appointments_limit ?? 20);
      return ok({ patient, appointments });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/create-patient.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var create_patient_default = defineTool3({
  name: "create_patient",
  title: "Cadastrar paciente",
  description: "Cria um novo paciente. Para menores de 18 anos, informe tamb\xE9m os dados do respons\xE1vel.",
  inputSchema: {
    name: z3.string().trim().min(2),
    cpf: z3.string().trim().min(1),
    phone: z3.string().trim().min(8).describe("Telefone com DDD; use + para n\xFAmeros internacionais."),
    email: z3.string().email().optional(),
    birth_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Formato AAAA-MM-DD."),
    address: z3.string().trim().optional(),
    notes: z3.string().trim().optional(),
    referral_source: z3.string().trim().optional(),
    guardian_name: z3.string().trim().optional(),
    guardian_cpf: z3.string().trim().optional(),
    guardian_phone: z3.string().trim().optional(),
    guardian_relationship: z3.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data, error } = await supabase.from("patients").insert({ ...input, is_active: true }).select().single();
      if (error) return fail(error.message);
      return ok({ patient: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/update-patient.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var update_patient_default = defineTool4({
  name: "update_patient",
  title: "Atualizar paciente",
  description: "Atualiza dados cadastrais, status de CRM, tags ou situa\xE7\xE3o (ativo/inativo) de um paciente.",
  inputSchema: {
    patient_id: z4.string().uuid(),
    name: z4.string().trim().min(2).optional(),
    phone: z4.string().trim().optional(),
    email: z4.string().email().optional(),
    address: z4.string().trim().optional(),
    notes: z4.string().trim().optional(),
    is_active: z4.boolean().optional(),
    crm_status: z4.string().trim().optional(),
    crm_status_locked: z4.boolean().optional(),
    crm_notes: z4.string().trim().optional(),
    crm_tags: z4.array(z4.string()).optional(),
    inactivation_reason: z4.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ patient_id, ...fields }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const patch = Object.fromEntries(Object.entries(fields).filter(([, v]) => v !== void 0));
      if (Object.keys(patch).length === 0) return fail("Nenhum campo informado para atualiza\xE7\xE3o.");
      const { data, error } = await supabase.from("patients").update(patch).eq("id", patient_id).select().single();
      if (error) return fail(error.message);
      return ok({ patient: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_appointments_default = defineTool5({
  name: "list_appointments",
  title: "Listar consultas",
  description: "Lista consultas da agenda por per\xEDodo, profissional, paciente ou status.",
  inputSchema: {
    date_from: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data inicial AAAA-MM-DD."),
    date_to: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data final AAAA-MM-DD."),
    professional_id: z5.string().uuid().optional(),
    patient_id: z5.string().uuid().optional(),
    status: z5.string().trim().optional().describe("ex.: agendado, confirmado, atendido, cancelado, Cliente Faltou."),
    limit: z5.number().int().min(1).max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to, professional_id, patient_id, status, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      let query = supabase.from("appointments").select(
        "id,appointment_date,appointment_time,duration_minutes,type,status,modality,appointment_mode,consultation_value,payment_method,payment_status,clinic_percentage,is_package,package_session_number,package_total_sessions,notes,patients(id,name,phone),professionals(id,name,specialty)"
      ).order("appointment_date", { ascending: false }).order("appointment_time", { ascending: true }).limit(limit ?? 100);
      if (date_from) query = query.gte("appointment_date", date_from);
      if (date_to) query = query.lte("appointment_date", date_to);
      if (professional_id) query = query.eq("professional_id", professional_id);
      if (patient_id) query = query.eq("patient_id", patient_id);
      if (status) query = query.eq("status", status);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return ok({ count: data?.length ?? 0, appointments: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/create-appointment.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var create_appointment_default = defineTool6({
  name: "create_appointment",
  title: "Agendar consulta",
  description: "Cria uma consulta na agenda. Verifica antes se o profissional j\xE1 tem outro atendimento no mesmo hor\xE1rio.",
  inputSchema: {
    patient_id: z6.string().uuid(),
    professional_id: z6.string().uuid(),
    appointment_date: z6.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    appointment_time: z6.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).describe("Hor\xE1rio HH:MM (08:00 a 21:00)."),
    duration_minutes: z6.number().int().min(10).max(240).default(50),
    type: z6.string().trim().default("consulta"),
    status: z6.string().trim().default("agendado"),
    modality: z6.string().trim().optional().describe("Presencial ou Online."),
    consultation_value: z6.number().nonnegative().optional(),
    clinic_percentage: z6.number().int().min(0).max(100).optional().describe("Comiss\xE3o da cl\xEDnica (padr\xE3o 25)."),
    is_package: z6.boolean().optional(),
    package_session_number: z6.number().int().min(1).optional(),
    package_total_sessions: z6.number().int().min(1).optional(),
    notes: z6.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data: conflict } = await supabase.from("appointments").select("id,appointment_time,status").eq("professional_id", input.professional_id).eq("appointment_date", input.appointment_date).eq("appointment_time", input.appointment_time).neq("status", "cancelado").maybeSingle();
      if (conflict) {
        return fail(
          `Conflito de hor\xE1rio: o profissional j\xE1 tem uma consulta em ${input.appointment_date} \xE0s ${input.appointment_time}.`
        );
      }
      const { data, error } = await supabase.from("appointments").insert({ ...input, created_by: ctx.getUserId() }).select().single();
      if (error) return fail(error.message);
      return ok({ appointment: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/update-appointment.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^4.4.3";
var update_appointment_default = defineTool7({
  name: "update_appointment",
  title: "Atualizar consulta",
  description: "Altera status, data, hor\xE1rio, valor ou observa\xE7\xF5es de uma consulta existente.",
  inputSchema: {
    appointment_id: z7.string().uuid(),
    status: z7.string().trim().optional().describe("ex.: agendado, confirmado, atendido, cancelado, Cliente Faltou."),
    appointment_date: z7.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    appointment_time: z7.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    duration_minutes: z7.number().int().min(10).max(240).optional(),
    modality: z7.string().trim().optional(),
    consultation_value: z7.number().nonnegative().optional(),
    payment_method: z7.string().trim().optional(),
    payment_status: z7.string().trim().optional(),
    notes: z7.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ appointment_id, ...fields }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const patch = Object.fromEntries(Object.entries(fields).filter(([, v]) => v !== void 0));
      if (Object.keys(patch).length === 0) return fail("Nenhum campo informado para atualiza\xE7\xE3o.");
      const { data, error } = await supabase.from("appointments").update(patch).eq("id", appointment_id).select().single();
      if (error) return fail(error.message);
      return ok({ appointment: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-professionals.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^4.4.3";
var list_professionals_default = defineTool8({
  name: "list_professionals",
  title: "Listar profissionais",
  description: "Lista os profissionais da cl\xEDnica com especialidade, valor de consulta, dias/hor\xE1rios de trabalho e turnos (sala, dia e per\xEDodo).",
  inputSchema: {
    search: z8.string().trim().optional().describe("Busca por nome ou especialidade."),
    is_active: z8.boolean().optional(),
    include_shifts: z8.boolean().default(true)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, is_active, include_shifts }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const columns = include_shifts === false ? "id,name,specialty,crp,phone,email,consultation_value,work_hours_start,work_hours_end,work_days,is_active" : "id,name,specialty,crp,phone,email,consultation_value,work_hours_start,work_hours_end,work_days,is_active,professional_shifts(room,day_of_week,shift_period)";
      let query = supabase.from("professionals").select(columns).order("name");
      if (search) query = query.or(`name.ilike.%${search}%,specialty.ilike.%${search}%`);
      if (typeof is_active === "boolean") query = query.eq("is_active", is_active);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return ok({ count: data?.length ?? 0, professionals: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/professional-earnings.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^4.4.3";
var professional_earnings_default = defineTool9({
  name: "professional_earnings",
  title: "Rendimento por profissional",
  description: "Resume, por profissional e per\xEDodo, quanto ficou para a cl\xEDnica e quanto foi pago ao profissional, com base nos pagamentos registrados.",
  inputSchema: {
    date_from: z9.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data inicial AAAA-MM-DD."),
    date_to: z9.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data final AAAA-MM-DD."),
    professional_id: z9.string().uuid().optional(),
    only_paid: z9.boolean().default(true).describe("Considerar apenas pagamentos j\xE1 confirmados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to, professional_id, only_paid }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      let query = supabase.from("professional_payments").select(
        "professional_id,total_value,professional_amount,clinic_amount,is_paid,professionals(name,specialty),appointments!inner(appointment_date,status)"
      ).gte("appointments.appointment_date", date_from).lte("appointments.appointment_date", date_to).neq("appointments.status", "cancelado");
      if (professional_id) query = query.eq("professional_id", professional_id);
      if (only_paid !== false) query = query.eq("is_paid", true);
      const { data, error } = await query;
      if (error) return fail(error.message);
      const totals = /* @__PURE__ */ new Map();
      for (const row of data ?? []) {
        const key = row.professional_id;
        const entry = totals.get(key) ?? {
          name: row.professionals?.name ?? "\u2014",
          specialty: row.professionals?.specialty ?? "\u2014",
          appointments: 0,
          clinic_revenue: 0,
          professional_revenue: 0,
          total: 0
        };
        entry.appointments += 1;
        entry.clinic_revenue += Number(row.clinic_amount ?? 0);
        entry.professional_revenue += Number(row.professional_amount ?? 0);
        entry.total += Number(row.total_value ?? 0);
        totals.set(key, entry);
      }
      const rows = [...totals.entries()].map(([professional_id2, v]) => ({ professional_id: professional_id2, ...v })).sort((a, b) => b.clinic_revenue - a.clinic_revenue);
      return ok({
        period: { date_from, date_to },
        only_paid: only_paid !== false,
        professionals: rows,
        totals: {
          clinic_revenue: rows.reduce((s, r) => s + r.clinic_revenue, 0),
          professional_revenue: rows.reduce((s, r) => s + r.professional_revenue, 0)
        }
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z10 } from "npm:zod@^4.4.3";
var financial_summary_default = defineTool10({
  name: "financial_summary",
  title: "Resumo financeiro",
  description: "Resumo financeiro do per\xEDodo: entradas e sa\xEDdas registradas em transa\xE7\xF5es (fonte \xFAnica de faturamento) e contas a pagar em aberto/pagas.",
  inputSchema: {
    date_from: z10.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    date_to: z10.string().regex(/^\d{4}-\d{2}-\d{2}$/)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data: transactions, error } = await supabase.from("transactions").select("type,amount,payment_method,transaction_date").gte("transaction_date", date_from).lte("transaction_date", date_to);
      if (error) return fail(error.message);
      let income = 0;
      let expense = 0;
      const byMethod = {};
      for (const t of transactions ?? []) {
        const amount = Number(t.amount ?? 0);
        if (t.type === "entrada" || t.type === "receita") {
          income += amount;
          const key = t.payment_method || "n\xE3o informado";
          byMethod[key] = (byMethod[key] ?? 0) + amount;
        } else {
          expense += amount;
        }
      }
      const { data: bills } = await supabase.from("bills_to_pay").select("status,amount,due_date,description,category").gte("due_date", date_from).lte("due_date", date_to);
      const billsPending = (bills ?? []).filter((b) => b.status !== "pago");
      const billsPaid = (bills ?? []).filter((b) => b.status === "pago");
      return ok({
        period: { date_from, date_to },
        transactions_count: transactions?.length ?? 0,
        income,
        expense,
        net: income - expense,
        income_by_payment_method: byMethod,
        bills: {
          pending_count: billsPending.length,
          pending_total: billsPending.reduce((s, b) => s + Number(b.amount ?? 0), 0),
          paid_count: billsPaid.length,
          paid_total: billsPaid.reduce((s, b) => s + Number(b.amount ?? 0), 0)
        }
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z11 } from "npm:zod@^4.4.3";
var list_transactions_default = defineTool11({
  name: "list_transactions",
  title: "Listar transa\xE7\xF5es",
  description: "Lista as movimenta\xE7\xF5es financeiras (entradas e sa\xEDdas) do per\xEDodo, opcionalmente filtradas por tipo ou profissional.",
  inputSchema: {
    date_from: z11.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    date_to: z11.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    type: z11.string().trim().optional().describe("ex.: entrada, saida."),
    professional_id: z11.string().uuid().optional(),
    limit: z11.number().int().min(1).max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to, type, professional_id, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      let query = supabase.from("transactions").select("id,type,description,amount,payment_method,transaction_date,transaction_time,professionals(name)").gte("transaction_date", date_from).lte("transaction_date", date_to).order("transaction_date", { ascending: false }).limit(limit ?? 100);
      if (type) query = query.eq("type", type);
      if (professional_id) query = query.eq("professional_id", professional_id);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return ok({ count: data?.length ?? 0, transactions: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-bills.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z12 } from "npm:zod@^4.4.3";
var list_bills_default = defineTool12({
  name: "list_bills",
  title: "Listar contas a pagar",
  description: "Lista as contas a pagar, com filtros por status, categoria e vencimento.",
  inputSchema: {
    status: z12.string().trim().optional().describe("ex.: pendente, pago, atrasado."),
    category: z12.string().trim().optional(),
    due_from: z12.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    due_to: z12.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    limit: z12.number().int().min(1).max(300).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, category, due_from, due_to, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      let query = supabase.from("bills_to_pay").select("id,description,amount,due_date,status,category,payment_method,paid_at,notes").order("due_date").limit(limit ?? 100);
      if (status) query = query.eq("status", status);
      if (category) query = query.eq("category", category);
      if (due_from) query = query.gte("due_date", due_from);
      if (due_to) query = query.lte("due_date", due_to);
      const { data, error } = await query;
      if (error) return fail(error.message);
      return ok({
        count: data?.length ?? 0,
        total: (data ?? []).reduce((s, b) => s + Number(b.amount ?? 0), 0),
        bills: data
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/create-bill.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z13 } from "npm:zod@^4.4.3";
var create_bill_default = defineTool13({
  name: "create_bill",
  title: "Criar conta a pagar",
  description: "Registra uma nova conta a pagar da cl\xEDnica.",
  inputSchema: {
    description: z13.string().trim().min(2),
    amount: z13.number().positive(),
    due_date: z13.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    category: z13.string().trim().optional(),
    payment_method: z13.string().trim().optional(),
    notes: z13.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data, error } = await supabase.from("bills_to_pay").insert({ ...input, status: "pendente", created_by: ctx.getUserId() }).select().single();
      if (error) return fail(error.message);
      return ok({ bill: data });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/dashboard-stats.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z14 } from "npm:zod@^4.4.3";
var REALIZED = ["atendido", "realizado", "concluido", "conclu\xEDdo"];
var dashboard_stats_default = defineTool14({
  name: "dashboard_stats",
  title: "Indicadores do dashboard",
  description: "Indicadores do per\xEDodo: faturamento recebido, consultas realizadas/pendentes/canceladas, taxa de realiza\xE7\xE3o, pacientes ativos e novos pacientes.",
  inputSchema: {
    date_from: z14.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    date_to: z14.string().regex(/^\d{4}-\d{2}-\d{2}$/)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data: appts, error } = await supabase.from("appointments").select("status").gte("appointment_date", date_from).lte("appointment_date", date_to);
      if (error) return fail(error.message);
      const list = appts ?? [];
      const realized = list.filter((a) => REALIZED.includes((a.status ?? "").toLowerCase())).length;
      const pending = list.filter((a) => a.status === "agendado" || a.status === "confirmado").length;
      const canceled = list.filter((a) => (a.status ?? "").toLowerCase() === "cancelado").length;
      const noShow = list.filter((a) => ["cliente faltou", "cliente_faltou", "faltou"].includes((a.status ?? "").toLowerCase())).length;
      const { data: transactions } = await supabase.from("transactions").select("type,amount").gte("transaction_date", date_from).lte("transaction_date", date_to);
      const revenue = (transactions ?? []).filter((t) => t.type === "entrada" || t.type === "receita").reduce((s, t) => s + Number(t.amount ?? 0), 0);
      const { count: activePatients } = await supabase.from("patients").select("*", { count: "exact", head: true }).eq("is_active", true);
      const { count: newPatients } = await supabase.from("patients").select("*", { count: "exact", head: true }).gte("registration_date", date_from).lte("registration_date", date_to);
      const base = realized + pending + canceled;
      return ok({
        period: { date_from, date_to },
        revenue_received: revenue,
        appointments: {
          total: list.length,
          realized,
          pending,
          canceled,
          no_show: noShow,
          realization_rate_pct: base > 0 ? Math.round(realized / base * 100) : 0
        },
        patients: { active: activePatients ?? 0, new_in_period: newPatients ?? 0 }
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/crm-overview.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z15 } from "npm:zod@^4.4.3";
var crm_overview_default = defineTool15({
  name: "crm_overview",
  title: "Panorama do CRM",
  description: "Distribui\xE7\xE3o dos pacientes por status de CRM (lead novo, em acompanhamento, risco de abandono, inativo, perdido...) e por tags autom\xE1ticas, com op\xE7\xE3o de listar os pacientes de um status.",
  inputSchema: {
    crm_status: z15.string().trim().optional().describe("Se informado, lista os pacientes deste status."),
    limit: z15.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ crm_status, limit }, ctx) => {
    try {
      const supabase = requireAuth(ctx);
      const { data, error } = await supabase.from("patients").select("id,name,phone,crm_status,crm_tags,crm_status_updated_at,is_active").eq("is_active", true);
      if (error) return fail(error.message);
      const byStatus = {};
      const byTag = {};
      for (const p of data ?? []) {
        const s = p.crm_status ?? "sem_status";
        byStatus[s] = (byStatus[s] ?? 0) + 1;
        for (const tag of p.crm_tags ?? []) byTag[tag] = (byTag[tag] ?? 0) + 1;
      }
      const patients = crm_status ? (data ?? []).filter((p) => p.crm_status === crm_status).sort((a, b) => (a.name ?? "").localeCompare(b.name ?? "")).slice(0, limit ?? 50) : void 0;
      return ok({ total_active: data?.length ?? 0, by_status: byStatus, by_tag: byTag, patients });
    } catch (e) {
      return fail(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "xayavfggzkgivgixfpqt";
var mcp_default = defineMcp({
  name: "remix-of-clinica-flow",
  title: "Remix of Cl\xEDnica Flow",
  version: "0.1.0",
  instructions: "Ferramentas do sistema de gest\xE3o da cl\xEDnica de psicologia Espa\xE7o Essentia Tiangu\xE1. Permite consultar e gerenciar pacientes, agenda de consultas, profissionais, financeiro (transa\xE7\xF5es e contas a pagar), indicadores do dashboard e o CRM de pacientes. Regras do neg\xF3cio: a tabela de transa\xE7\xF5es \xE9 a \xFAnica fonte de faturamento; a comiss\xE3o da cl\xEDnica \xE9 de 25%; a sess\xE3o padr\xE3o dura 50 minutos; salas dispon\xEDveis: Harmonia, Serenidade, Florescer e Online. Datas usam o formato AAAA-MM-DD. Todas as chamadas respeitam as permiss\xF5es do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_patients_default,
    get_patient_default,
    create_patient_default,
    update_patient_default,
    list_appointments_default,
    create_appointment_default,
    update_appointment_default,
    list_professionals_default,
    professional_earnings_default,
    financial_summary_default,
    list_transactions_default,
    list_bills_default,
    create_bill_default,
    dashboard_stats_default,
    crm_overview_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
